# Generated by Django 5.1.6 on 2025-02-07 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('q_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('q_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('open_ended', 'Open Ended')], default='open_ended', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('c_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='questions.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('a_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('selected_choices', models.ManyToManyField(blank=True, to='questions.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
        ),
    ]
