# Generated by Django 5.1.2 on 2025-07-15 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('q_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('section', models.PositiveIntegerField(default=1)),
                ('q_type', models.CharField(choices=[('multiple_choice_single', 'Multiple Choice Single'), ('multiple_choice_multiple', 'Multiple Choice Multiple'), ('open_ended', 'Open Ended'), ('datetime', 'Date/Time Input'), ('single_choice_other', 'Single Choice with Other'), ('multiple_choice_other', 'Multiple Choice with Other'), ('multi_text', 'Multiple Text Fields'), ('number_range', 'Number Range'), ('slider', 'Slider')], default='open_ended', max_length=24)),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('max_value', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nickname', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('matching_code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('c_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='questions.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('a_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_choice_answers', to='questions.choice')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='multiple_choice_answers', to='questions.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.usersession')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyzableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_min', models.PositiveIntegerField(blank=True, null=True)),
                ('age_max', models.PositiveIntegerField(blank=True, null=True)),
                ('height_min', models.PositiveIntegerField(blank=True, null=True)),
                ('height_max', models.PositiveIntegerField(blank=True, null=True)),
                ('zodiac_sign', models.CharField(blank=True, max_length=20, null=True)),
                ('romance_score', models.FloatField(blank=True, null=True)),
                ('relationship_status', models.CharField(blank=True, max_length=50, null=True)),
                ('desired_relationship_type', models.CharField(blank=True, max_length=50, null=True)),
                ('libido_score', models.FloatField(blank=True, null=True)),
                ('extroversion_score', models.FloatField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyzable_data', to='questions.usersession')),
            ],
        ),
    ]
