# Generated by Django 5.1.6 on 2025-02-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_q_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
