# Generated by Django 5.1.6 on 2025-07-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_populate_all_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzabledata',
            name='attraction_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
