# Generated by Django 5.1.2 on 2025-03-03 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_answer_selected_choice_alter_answer_selected_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nickname', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('matching_code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='user_name',
        ),
        migrations.AddField(
            model_name='answer',
            name='session',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='questions.usersession'),
            preserve_default=False,
        ),
    ]
