# Generated by Django 5.1.6 on 2025-03-03 10:58

from django.db import migrations

def add_questions_and_choices(apps, schema_editor):
    Question = apps.get_model('questions', 'Question')
    Choice = apps.get_model('questions', 'Choice')

    # Question 1: İsim Soyisim
    q1 = Question.objects.create(
        text="İsim Soyisim",
        section=1,
        q_type="open_ended"
    )

    # Question 2: Doğum Tarihi ve Doğum Saati
    q2 = Question.objects.create(
        text="Doğum Tarihi ve Doğum Saati",
        section=1,
        q_type="open_ended"
    )

    # Question 3: Cinsiyet
    q3 = Question.objects.create(
        text="Cinsiyet",
        section=1,
        q_type="multiple_choice_single"
    )
    # Choices for Cinsiyet
    Choice.objects.create(question=q3, text="Erkek")
    Choice.objects.create(question=q3, text="Kadın")
    Choice.objects.create(question=q3, text="Diğer")

    # Question 4: Yönelim
    q4 = Question.objects.create(
        text="Yönelim",
        section=1,
        q_type="multiple_choice_single"
    )
    # Choices for Yönelim
    Choice.objects.create(question=q4, text="Heteroseksüel")
    Choice.objects.create(question=q4, text="Homoseksüel")
    Choice.objects.create(question=q4, text="Diğer")

    # Question 5: İlişki Durumu
    q5 = Question.objects.create(
        text="İlişki Durumu",
        section=1,
        q_type="multiple_choice_single"
    )
    # Choices for İlişki Durumu
    Choice.objects.create(question=q5, text="İlişkim var")
    Choice.objects.create(question=q5, text="İlişkim yok")
    Choice.objects.create(question=q5, text="Karışık")
    Choice.objects.create(question=q5, text="Diğer")

    # Question 6: IG Nickname
    q6 = Question.objects.create(
        text="Instagram Kullanıcı Adı",
        section=1,
        q_type="open_ended"
    )

def remove_questions_and_choices(apps, schema_editor):
    Question = apps.get_model('questions', 'Question')
    Question.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_usersession_remove_answer_user_name_answer_session'),
    ]

    operations = [
        migrations.RunPython(add_questions_and_choices, remove_questions_and_choices),
    ]
