# Generated by Django 5.1.6 on 2025-03-03 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_add_initial_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_min', models.PositiveIntegerField(blank=True, null=True)),
                ('age_max', models.PositiveIntegerField(blank=True, null=True)),
                ('height_min', models.PositiveIntegerField(blank=True, null=True)),
                ('height_max', models.PositiveIntegerField(blank=True, null=True)),
                ('zodiac_sign', models.CharField(blank=True, max_length=20, null=True)),
                ('romance_score', models.FloatField(blank=True, null=True)),
                ('relationship_status', models.CharField(blank=True, max_length=50, null=True)),
                ('desired_relationship_type', models.CharField(blank=True, max_length=50, null=True)),
                ('libido_score', models.FloatField(blank=True, null=True)),
                ('extroversion_score', models.FloatField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyzable_data', to='questions.usersession')),
            ],
        ),
    ]
